//! PR body renderer.
//!
//! Composes the structured PR description assay opens. Every
//! upstream-supplied string (release notes, tag name, commit subject)
//! is routed through `crate::sanitize` before interpolation.

use std::path::PathBuf;

use crate::model::{Classification, Proposal, ValidationOutcome};
use crate::sanitize::sanitize_release_notes;

/// Inputs the renderer needs that aren't on `Proposal` itself.
#[derive(Debug, Clone)]
pub struct PrBodyContext {
    pub repository: String,
    pub run_id: String,
    /// Workspace-relative path of the persisted assay receipt
    /// (typically `.assay/runs/<id>/run.json`).
    pub receipt_path: PathBuf,
    /// Release notes for the new version, if available. Sanitized by
    /// the renderer.
    pub release_notes: Option<String>,
}

/// Render a complete PR description for one proposal + its validation.
pub fn render_pr_body(
    proposal: &Proposal,
    outcome: &ValidationOutcome,
    ctx: &PrBodyContext,
) -> String {
    let mut body = String::new();
    body.push_str("## Bump\n\n");
    body.push_str(&format!(
        "- **{subject}**: `{from}` → `{to}` ({ecosystem})\n",
        subject = proposal.subject,
        from = proposal.from,
        to = proposal.to,
        ecosystem = proposal.ecosystem,
    ));
    body.push_str(&format!(
        "- Initial classification: `{}`\n",
        proposal.initial_classification.as_str()
    ));
    body.push_str(&format!(
        "- Post-validation classification: `{}`\n",
        outcome.classification.as_str()
    ));
    body.push_str(&format!(
        "- Validation conclusion: `{}`\n\n",
        outcome.conclusion
    ));

    body.push_str("## Validation\n\n");
    if outcome.ci_forge_run_ids.is_empty() {
        body.push_str(
            "_No ci-forge run was recorded for this proposal — see classification above._\n\n",
        );
    } else {
        body.push_str("ci-forge run id(s):\n");
        for run_id in &outcome.ci_forge_run_ids {
            body.push_str(&format!("- `{run_id}`\n"));
        }
        body.push('\n');
        if !outcome.validated_workflows.is_empty() {
            body.push_str("Workflows validated:\n");
            for path in &outcome.validated_workflows {
                body.push_str(&format!("- `{}`\n", path.display()));
            }
            body.push('\n');
        }
    }

    if matches!(
        outcome.classification,
        Classification::Compatible | Classification::Simulated | Classification::Stubbed
    ) {
        body.push_str("> ⚠️ Local validation is not identical to GitHub-hosted behavior. ");
        body.push_str("Some receipt entries were `compatible`/`simulated`/`stubbed`; review the ");
        body.push_str("attached run receipt before merging.\n\n");
    }

    if !outcome.notes.is_empty() {
        body.push_str("## Notes\n\n");
        for note in &outcome.notes {
            body.push_str(&format!("- {note}\n"));
        }
        body.push('\n');
    }

    if let Some(notes) = ctx.release_notes.as_deref().filter(|s| !s.is_empty()) {
        body.push_str("## Upstream Release Notes\n\n");
        body.push_str(&sanitize_release_notes(notes));
        body.push_str("\n\n");
    }

    body.push_str("## Provenance\n\n");
    body.push_str(&format!("- Repository: `{}`\n", ctx.repository));
    body.push_str(&format!("- assay run id: `{}`\n", ctx.run_id));
    body.push_str(&format!(
        "- Local receipt: `{}`\n",
        ctx.receipt_path.display()
    ));
    body.push_str(
        "\n---\n_Generated by `assay`. Validation runs against ci-forge's local execution, \
        not GitHub Actions hosted runners — see the run receipt for any classification differences._\n",
    );
    body
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::ProposalKind;

    fn sample_proposal() -> Proposal {
        Proposal {
            id: "cargo-serde-1-0-215-abc".into(),
            ecosystem: "cargo".into(),
            kind: ProposalKind::Version,
            subject: "serde".into(),
            from: "1.0.200".into(),
            to: "1.0.215".into(),
            initial_classification: Classification::Exact,
            manifest_paths: vec![],
            notes: vec![],
            bump_tier: crate::model::BumpTier::LockfileOnly,
            affected_consumers: Vec::new(),
        }
    }

    fn sample_outcome(conclusion: &str, classification: Classification) -> ValidationOutcome {
        ValidationOutcome {
            proposal_id: "cargo-serde-1-0-215-abc".into(),
            conclusion: conclusion.into(),
            ci_forge_run_ids: vec!["local-1779000000000".into()],
            validated_workflows: vec![PathBuf::from(".github/workflows/ci.yml")],
            classification,
            notes: vec![],
            failure_details: vec![],
        }
    }

    fn sample_ctx() -> PrBodyContext {
        PrBodyContext {
            repository: "wildmason/example".into(),
            run_id: "assay-1779000000000".into(),
            receipt_path: ".assay/runs/assay-1779000000000/run.json".into(),
            release_notes: None,
        }
    }

    #[test]
    fn body_contains_bump_subject_versions_classification() {
        let body = render_pr_body(
            &sample_proposal(),
            &sample_outcome("success", Classification::Exact),
            &sample_ctx(),
        );
        assert!(body.contains("**serde**"));
        assert!(body.contains("`1.0.200`"));
        assert!(body.contains("`1.0.215`"));
        assert!(body.contains("`exact`"));
        assert!(body.contains("`success`"));
        assert!(body.contains("local-1779000000000"));
        assert!(body.contains(".github/workflows/ci.yml"));
        assert!(body.contains("wildmason/example"));
        assert!(body.contains(".assay/runs/assay-1779000000000/run.json"));
    }

    #[test]
    fn body_surfaces_warning_on_non_exact_classification() {
        for classification in [
            Classification::Compatible,
            Classification::Simulated,
            Classification::Stubbed,
        ] {
            let body = render_pr_body(
                &sample_proposal(),
                &sample_outcome("success", classification),
                &sample_ctx(),
            );
            assert!(
                body.contains("not identical to GitHub-hosted behavior"),
                "missing warning for {classification:?}: {body}"
            );
        }
    }

    #[test]
    fn body_omits_warning_for_exact_classification() {
        let body = render_pr_body(
            &sample_proposal(),
            &sample_outcome("success", Classification::Exact),
            &sample_ctx(),
        );
        assert!(!body.contains("not identical to GitHub-hosted behavior"));
    }

    #[test]
    fn body_sanitizes_release_notes_before_embedding() {
        let mut ctx = sample_ctx();
        ctx.release_notes =
            Some(r#"<img src=x onerror=alert(1)> see <a href="javascript:hi">"#.into());
        let body = render_pr_body(
            &sample_proposal(),
            &sample_outcome("success", Classification::Exact),
            &ctx,
        );
        // Sanitizer must have HTML-escaped the hostile content.
        assert!(body.contains("&lt;img"), "must escape: {body}");
        assert!(!body.contains("<img src"), "raw tag leaked: {body}");
        // And the content must be code-fenced.
        assert!(body.contains("````"), "must code-fence: {body}");
    }

    #[test]
    fn body_handles_unvalidated_outcome() {
        let outcome = ValidationOutcome {
            proposal_id: "cargo-serde-x".into(),
            conclusion: "unvalidated".into(),
            ci_forge_run_ids: vec![],
            validated_workflows: vec![],
            classification: Classification::Stubbed,
            notes: vec!["no affected workflow identified".into()],
            failure_details: vec![],
        };
        let body = render_pr_body(&sample_proposal(), &outcome, &sample_ctx());
        assert!(body.contains("No ci-forge run was recorded"));
        assert!(body.contains("no affected workflow identified"));
        // Stubbed → warning surfaces.
        assert!(body.contains("not identical to GitHub-hosted behavior"));
    }

    #[test]
    fn body_includes_provenance_footer() {
        let body = render_pr_body(
            &sample_proposal(),
            &sample_outcome("success", Classification::Exact),
            &sample_ctx(),
        );
        assert!(body.contains("## Provenance"));
        assert!(body.contains("Generated by `assay`"));
    }
}
